dist: trusty
sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_script:
  - composer install -n

script:
  - vendor/bin/phpunit

cache:
  directories:
  - vendor
